apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: comrade-chatgpt-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      initContainers:
        - name: liquibase
          image: zika13/comrade-chatgpt-bot:liquibase_not_in_use
          args: [
            "--changeLogFile=initial.postgres.yaml",
            "--url=jdbc:postgresql://postgres:5432/bot",
            "update"
          ]
          env:
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST

      containers:
        - name: telegram-bot
          image: zika13/comrade-chatgpt-bot:telegram_bot_not_in_use
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: IMAGE_PRICE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: IMAGE_PRICE
